-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- Create a table for stickers
create table user_stickers (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  sticker_number integer not null,
  count integer default 0,
  
  unique(user_id, sticker_number)
);

alter table user_stickers enable row level security;

create policy "Stickers are viewable by everyone." on user_stickers
  for select using (true);

create policy "Users can insert their own stickers." on user_stickers
  for insert with check ((select auth.uid()) = user_id);

create policy "Users can update own stickers." on user_stickers
  for update using ((select auth.uid()) = user_id);

-- Function to handle new user creation automatically
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
